# Generated by Django 4.0 on 2022-01-20 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom du Client')),
                ('prenom', models.CharField(max_length=120, verbose_name='Prenom du  Client')),
                ('adresse', models.CharField(max_length=120, verbose_name='adresse du Client')),
                ('tel', models.CharField(max_length=120, verbose_name='Telephone du Client')),
                ('profession', models.CharField(max_length=50, verbose_name='Profession du Client')),
            ],
        ),
        migrations.CreateModel(
            name='Personnels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom du Personnel')),
                ('prenom', models.CharField(max_length=120, verbose_name='Prenom du  Personnel')),
                ('adresse', models.CharField(max_length=120, verbose_name='Adresse du Personnel')),
                ('tel', models.CharField(max_length=120, verbose_name='Telephone du Personnel')),
                ('email', models.EmailField(max_length=254, verbose_name='Email du Personnel')),
                ('statut', models.CharField(max_length=50, verbose_name='Statut du Personnel')),
                ('specialite', models.CharField(max_length=50, verbose_name='specialite du Personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Dossiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Date de reception')),
                ('statut', models.CharField(max_length=50, verbose_name='Statut du Dossier')),
                ('categorie', models.CharField(max_length=50, verbose_name='Categorie du Dossier')),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocatsApp.clients')),
                ('personnels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocatsApp.personnels')),
            ],
        ),
    ]
