# Generated by Django 4.0 on 2022-01-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocatsApp', '0004_dossiers_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnels',
            name='grade',
            field=models.CharField(default='', max_length=50, verbose_name='Grade du Personnel'),
            preserve_default=False,
        ),
    ]
