# Generated by Django 4.0 on 2022-01-25 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avocatsApp', '0005_personnels_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiers',
            name='clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocatsApp.clients'),
        ),
        migrations.AlterField(
            model_name='dossiers',
            name='personnels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocatsApp.personnels'),
        ),
    ]
