# Generated by Django 4.0 on 2022-04-13 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avocatsApp', '0007_alter_dossiers_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date de reception')),
                ('categorie', models.CharField(max_length=50, verbose_name='Categorie de la Redaction')),
                ('description', models.TextField(verbose_name='Description de la Redaction')),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocatsApp.clients')),
                ('personnels', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocatsApp.personnels')),
            ],
        ),
        migrations.CreateModel(
            name='Conseils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date de reception')),
                ('categorie', models.CharField(max_length=50, verbose_name='Categorie du Conseil')),
                ('description', models.TextField(verbose_name='Description du Conseil')),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocatsApp.clients')),
                ('personnels', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocatsApp.personnels')),
            ],
        ),
    ]
