# Generated by Django 4.0 on 2022-06-28 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Societe')),
                ('prenom', models.CharField(max_length=50, verbose_name='Prenom du Client')),
                ('sexe', models.CharField(choices=[('F', 'Feminin'), ('M', 'Masculin')], max_length=10, null=True)),
                ('adresse', models.CharField(choices=[('1er Arrondissement', '1er Arrondissemnt'), ('2eme Arrondissement', '2eme Arrondissemnt'), ('3eme Arrondissement', '3eme Arrondissemnt'), ('4eme Arrondissement', '4eme Arrondissemnt'), ('5eme Arrondissement', '5eme Arrondissemnt'), ('6eme Arrondissement', '6eme Arrondissemnt'), ('7eme Arrondissement', '7eme Arrondissemnt'), ('8eme Arrondissement', '8eme Arrondissemnt'), ('9eme Arrondissement', '9eme Arrondissemnt'), ('10eme Arrondissement', '10eme Arrondissemnt')], max_length=20, null=True)),
                ('number', models.CharField(max_length=50, verbose_name='Carte d_identite')),
                ('delivrate', models.CharField(max_length=150, verbose_name='Delivre le')),
                ('qualite', models.CharField(choices=[('Demandeur', 'Demandeur'), ('Defendeur', 'Defendeur'), ('Appelant', 'Appelant'), ('Intimé', 'Intimé'), ('Demandeur au pourvoir', 'Demandeur au pourvoir'), ('Defenseur au pourvoir', 'Defenseur au pourvoir'), ('Prevenu', 'Prevenu'), ('Partie Civile', 'Partie civile'), ('Civilement Responsable', 'Civilement Responsable'), ('Mise en cause', 'Mise en cause'), ('Intervenant', 'Intervenant')], max_length=150, null=True)),
                ('tel', models.CharField(max_length=120, verbose_name='Telephone du Client')),
                ('profession', models.CharField(max_length=50, verbose_name='Profession du Client')),
            ],
        ),
        migrations.CreateModel(
            name='Dossiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date de reception')),
                ('contre', models.CharField(max_length=50, verbose_name='Contre')),
                ('avocat_adverse', models.CharField(max_length=50, verbose_name='Avocat Adverse')),
                ('detail_juridiction', models.CharField(max_length=50, verbose_name='Juridiction')),
                ('nature', models.CharField(max_length=150, verbose_name='Nature')),
                ('reclamation', models.CharField(max_length=50, verbose_name='Reclamation')),
                ('objet', models.CharField(max_length=50, verbose_name='Objet')),
                ('commentaire', models.TextField(verbose_name='commentaire')),
                ('avocat', models.CharField(choices=[('Me TOG', 'Me TOG'), ('Me Clotilde', 'Me Clotilde'), ('Me MOUSSA', 'Me MOUSSA')], max_length=50, null=True)),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocatsApp.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Personnels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom du Personnel')),
                ('prenom', models.CharField(max_length=120, verbose_name='Prenom du  Personnel')),
                ('adresse', models.CharField(max_length=120, verbose_name='Adresse du Personnel')),
                ('tel', models.CharField(max_length=120, verbose_name='Telephone du Personnel')),
                ('email', models.EmailField(max_length=254, verbose_name='Email du Personnel')),
                ('domaine', models.CharField(max_length=150, verbose_name='domaine du Personnel')),
                ('specialite', models.CharField(max_length=50, verbose_name='specialite du Personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Honoraires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date de reception')),
                ('payement', models.CharField(choices=[('Cheque', 'Cheque'), ('Virement', 'Virement'), ('Cash', 'Cash')], max_length=20, null=True)),
                ('total', models.PositiveIntegerField(verbose_name='Total')),
                ('reste', models.PositiveIntegerField(verbose_name=' Reste')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant')),
                ('clientss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocatsApp.clients')),
                ('dossierss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocatsApp.dossiers')),
                ('personnels01', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocatsApp.personnels')),
            ],
        ),
        migrations.AddField(
            model_name='dossiers',
            name='personnels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocatsApp.personnels'),
        ),
        migrations.CreateModel(
            name='Conseils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date de reception')),
                ('categorie', models.CharField(max_length=50, verbose_name='Categorie du Conseil')),
                ('description', models.TextField(verbose_name='Description du Conseil')),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocatsApp.clients')),
                ('personnels', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocatsApp.personnels')),
            ],
        ),
        migrations.CreateModel(
            name='Audiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date de reception')),
                ('statut', models.CharField(max_length=40, verbose_name='Statut')),
                ('subtitution', models.CharField(max_length=50, verbose_name='Subtitution')),
                ('personne', models.CharField(max_length=50, verbose_name='Personne en Charge')),
                ('juridiction', models.CharField(max_length=50, verbose_name='Juridiction')),
                ('commentaire', models.CharField(max_length=150, verbose_name='Commentaire')),
                ('clients_audience1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocatsApp.clients')),
                ('dossiers_audience1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avocatsApp.dossiers')),
                ('personnels_audience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avocatsApp.personnels')),
            ],
        ),
    ]
