# Generated by Django 4.0 on 2022-06-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avocatsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossiers',
            name='reclamation',
        ),
        migrations.AlterField(
            model_name='audiences',
            name='commentaire',
            field=models.CharField(max_length=150, verbose_name='Decisions'),
        ),
        migrations.AlterField(
            model_name='audiences',
            name='date',
            field=models.DateTimeField(verbose_name="Date d'audience"),
        ),
        migrations.AlterField(
            model_name='audiences',
            name='personne',
            field=models.CharField(max_length=50, verbose_name='Chambre en Charge'),
        ),
        migrations.AlterField(
            model_name='dossiers',
            name='commentaire',
            field=models.TextField(max_length=50, verbose_name='Reclamation'),
        ),
    ]
